### ISSUE TITLE
Berkshelf crashes on OS X

### ISSUE THREAD

**Issue by damphyr** [Zuehlke/cookbook-elk-stack#13]
After getting all the plugins and installing ChefDK 0.10

```
Git error: command `git reset --hard b38d2381b1e4e40b4674be47c105e88f38f47fbd` failed. If this error persists, try removing the cache directory at '.berkshelf/.cache/git/7f10b9ff6ae4c9fbcf8f1fdaa1bc8959b12ec92e'.Output from the command:

fatal: Could not parse object 'b38d2381b1e4e40b4674be47c105e88f38f47fbd'.
```

**Comment by damphyr** [comment]
Reinstalling ChefDK *and* vagrant, then reinstalling the vagrant plugins solves the problem.
Current combo that works is ChefDK 0.10.0 and Vagrant 1.8.1

**Comment by tknerr** [comment]
weird... why did you have to reinstall?!

And: 

 * does it only work for `vagrant up`? 
 * or for `bundle install` as well (I might have [locked the berkshelf gem](https://github.com/Zuehlke/cookbook-elk-stack/blob/master/Gemfile#L4) to a version that is problematic with OSX?)?

**Comment by tknerr** [comment]
Darn, I need a Mac (and everyone else too ;-)) so we can solve the problems on a single platform :)
